### ISSUE TITLE
Failed to load http://localhost:8069/web/session/authenticate

### ISSUE THREAD

**Issue by HardieChristie** [karthikrp/angular6-odoo-jsonrpc#1]
Hello !

I'm facing that problem : 
**OPTIONS http://localhost:8069/web/session/authenticate 400 (BAD REQUEST)**
**Failed to load http://localhost:8069/web/session/authenticate: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.**

Here is my code : 
import {Component, OnInit} from '@angular/core';
import {Ng6OdooRPCService} from 'angular6-odoo-jsonrpc';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';

@Component({
  selector: 'app-auth',
  templateUrl: './auth.component.html',
  styleUrls: ['./auth.component.css'],
  providers: [Ng6OdooRPCService]
})
export class AuthComponent implements OnInit {

  loginForm: FormGroup;
  submitted = false;
  loading = false;
  db_name = 'tpl_bd';

  constructor(private odooRPC: Ng6OdooRPCService,
              private frombuilder: FormBuilder) {}

  ngOnInit() {
    this.loginForm = this.frombuilder.group({
      username: ['', Validators.required],
      password: ['', Validators.required]
    });
  }

  // get Form
  get f() {
    return this.loginForm.controls;
  }

  onSubmit() {
    this.submitted = true;
    if (this.loginForm.invalid) {
      return;
    }

    this.loading = true;
    this.odooRPC.init({
      odoo_server: 'http://localhost:8069',
      // http_auth: 'username:password' // optional
    });

    this.odooRPC.login(this.db_name, this.f.username.value, this.f.password.value).then(res => {
      console.log('Access');
    }).catch(err => {
      alert(this.db_name);
      alert(this.f.username.value);
      alert(this.f.password.value);
      console.error(' No access !', err);
    });
  }

}

Anyone could help me please ?

**Comment by bylli79** [comment]
Hello
I have the same problem too.
Has anyone solved it?

Thank you

**Comment by HardieChristie** [comment]
I've solved it using cors for browser but I don't like that solution, i need another.

**Comment by bylli79** [comment]
I have also tried the CORS but it does not work.
Would you explain to me how you did?

Thank you

**Comment by HardieChristie** [comment]
if you use firefox, add this addon -> https://addons.mozilla.org/en-US/firefox/addon/access-control-allow-origin/ or https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi if you use chrome.

**Comment by blended-ideas** [comment]
Closing this issue.
If you get a CORS issue then you need to enable CORS and white list the domain at backend.

**Comment by abhijeetgiram** [comment]
@karthikrp I still facing the issue. Need Help

I have added CORS. But got an error as

OPTIONS http://127.0.0.1:8069/web/session/authenticate 400 (BAD REQUEST)

Access to XMLHttpRequest at 'http://127.0.0.1:8069/web/session/authenticate' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status

**Comment by abhijeetgiram** [comment]
> Hello !
> 
> I'm facing that problem :
> **OPTIONS http://localhost:8069/web/session/authenticate 400 (BAD REQUEST)**
> **Failed to load http://localhost:8069/web/session/authenticate: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.**
> 
> Here is my code :
> import {Component, OnInit} from '@angular/core';
> import {Ng6OdooRPCService} from 'angular6-odoo-jsonrpc';
> import {FormBuilder, FormGroup, Validators} from '@angular/forms';
> 
> @component({
> selector: 'app-auth',
> templateUrl: './auth.component.html',
> styleUrls: ['./auth.component.css'],
> providers: [Ng6OdooRPCService]
> })
> export class AuthComponent implements OnInit {
> 
> loginForm: FormGroup;
> submitted = false;
> loading = false;
> db_name = 'tpl_bd';
> 
> constructor(private odooRPC: Ng6OdooRPCService,
> private frombuilder: FormBuilder) {}
> 
> ngOnInit() {
> this.loginForm = this.frombuilder.group({
> username: ['', Validators.required],
> password: ['', Validators.required]
> });
> }
> 
> // get Form
> get f() {
> return this.loginForm.controls;
> }
> 
> onSubmit() {
> this.submitted = true;
> if (this.loginForm.invalid) {
> return;
> }
> 
> ```
> this.loading = true;
> this.odooRPC.init({
>   odoo_server: 'http://localhost:8069',
>   // http_auth: 'username:password' // optional
> });
> 
> this.odooRPC.login(this.db_name, this.f.username.value, this.f.password.value).then(res => {
>   console.log('Access');
> }).catch(err => {
>   alert(this.db_name);
>   alert(this.f.username.value);
>   alert(this.f.password.value);
>   console.error(' No access !', err);
> });
> ```
> }
> 
> }
> 
> Anyone could help me please ?

**Comment by blended-ideas** [comment]
@AbhijeetGiram 
As I said, this is not an issue at the front end. It's the backend that handles CORS policy.
This issue has nothing to do with angular.
