### ISSUE TITLE
How to use domain parameter in searchRead() function ?

### ISSUE THREAD

**Issue by HardieChristie** [karthikrp/angular6-odoo-jsonrpc#2]
Hello !

Is there anyone who knows how to use **domain** parameter in **searchRead()** function of **angular6-odoo-jsonrpc** please? Thank you!
![io](https://user-images.githubusercontent.com/43638084/47410468-96bad080-d76e-11e8-8e28-2bfefba95e0d.png)

**Comment by blended-ideas** [comment]
You can directly send an prefix array(based on how your odoo server accepts conditions). 


    const domain = ['|', ['name', '=', 'HardieChristie'],  ['country', 'ilike', 'USA']];
     
    this.odooRPC.searchRead('employee.data', domain, ['name'], 10, 0, {}, "write_date DESC")
    .then((response) => {
    });

**Comment by HardieChristie** [comment]
Thank you so much for your response :-)
This is an example of how my odoo server accepts condition : 
![io2](https://user-images.githubusercontent.com/43638084/47656690-953f3d00-dba0-11e8-9fd2-f262fc86fa0b.png) 
so I write my domain like this : 
![io1](https://user-images.githubusercontent.com/43638084/47656732-b4d66580-dba0-11e8-845b-705cef5fdfed.png)
And it tells that :
![io](https://user-images.githubusercontent.com/43638084/47656790-d9324200-dba0-11e8-96d2-f72cd073033e.png)

**Comment by blended-ideas** [comment]
Javascript doesn't have tuples. Try using array instead.

const domain = [['category_id', '=', 1]];
This should work.

**Comment by HardieChristie** [comment]
It works perfectly. Thank you so much :-)
