### ISSUE TITLE
API is failing continuously

### ISSUE THREAD

**Issue by abhijeetgiram** [karthikrp/angular6-odoo-jsonrpc#4]
![odoo error stack trace](https://user-images.githubusercontent.com/16386383/51661300-781ade80-1fd6-11e9-9e71-6965ae23bf80.png)

Can u help me to solve this issue? Why am I getting this error?
Because this API call is working successfully for the first time but then now failing continuously. 
Need help.

**Comment by blended-ideas** [comment]
Says 404 Not found, Its an invalid URL. Check the url you are hitting.

**Comment by abhijeetgiram** [comment]
The URL is working most of the time after clearing site data. 
But for next time after the success, the same URL gives above error.

**Comment by blended-ideas** [comment]
Check the stack trace for the URL which you are attempting to hit.
Closing the issue, does not have anything to do with the package.
